### ISSUE TITLE
This Tool is Too Good

### ISSUE THREAD

**Issue by beldenge** [M3tox/DFET#1]
The only issue is that this tool is too awesome.  I'm sorry for communicating this through a (non) issue, but I did not know any other way to let you know that your hard work is recognized and greatly appreciated.  I have used this tool to extract sound and images from Dust, and it's worked amazingly well.  I was honestly shocked that anyone had actually taken the time to produce something like this.  As a big fan of the games produced with DreamFactory, I hope to do something cool with the assets your tool has given me access to.  My sincere thanks to you for your efforts!

**Comment by M3tox** [comment]
Thank you very much, I really appreciate your feedback :) It's great to see that people are using this to create awesome stuff!
