### ISSUE TITLE
Support for DreamFactory 5.0

### ISSUE THREAD

**Issue by Puterboy1** [M3tox/DFET#4]
Any possibility that in the distant future, this program could support DreamFactory 5.0 games like Redjack, Disney's Villain's Revenge and The D Show?

**Comment by M3tox** [comment]
I should never say never, but it is very unlikely that it will support anything beyond version 4.0.
DFET is considered to be done and finished when all files of "DUST" can be extracted. I will focus on other projects after this.

**Comment by Puterboy1** [comment]
So there is still a chance?
