### ISSUE TITLE
Hi, I'm new on this

### ISSUE THREAD

**Issue by VerdeCreeper** [M3tox/DFET#5]
Hi, I was finding a way to extracts the files of a game I have called Disney's Villains' Revenge, which was made on Dream Factory 5.0, and this is the only result I found on Google. However, I have two problems:

I never opened a cpp file, so i don't know how to run it, or I should open another file that I'm missing.

And the other question is that DFET supports Dream Factory 5.0, or only up to 4.0

Thanks!

**Comment by M3tox** [comment]
To use DFET you don't need the cpp files, these are only for programmers who want to use the code to make their own applications with it. The current version of DFET Version 0.89 can be downloaded in the relese section, which is a built executive to run on windwos.
However, it does NOT support anything beyond version 4.0, so it will probably not help you with your game "Disney's Villains' Revenge". Will DFET eventually be updated to support version 5 at some point? No, probably not.
