### ISSUE TITLE
Early DreamFactory support?

### ISSUE THREAD

**Issue by nomakewan** [M3tox/DFET#6]
Hello,

Apologies as I did see that you had no intention of adding support for versions of DreamFactory _after_ 4.0, but what about versions _before_ 4.0? I would love to be able to extract the files from Jump Raven or Lunicus, and am particularly interested in the music from Jump Raven.

Great job making this tool, and best of luck with the DUST compatibility!

**Comment by M3tox** [comment]
Hello and thank you very much. Right now the tool is only focused between Version 1.0 (DUST) and Version 4.0 (Titanic). Any compatibility before "DUST" is not planned.
