### ISSUE TITLE
Support for "Disney's Math Quest with Aladdin" and "Lunicus"

### ISSUE THREAD

**Issue by Corak667** [M3tox/DFET#7]
There's also some games, that aren't supported normally by your tool:
"Disney's Math Quest with Aladdin" ( Logic-Math / 1997 / Win32-MacOS )
https://cloud.mail.ru/public/Booo/hHK6rqtrh

Lunicus ( Quest-3daction / 1994 / MacOS-Win16 )
_Win16_Game: https://vk.com/doc-65855514_445327053
_MacOS_Game: https://vk.com/doc-65855514_445326818
CloudFull:  https://cloud.mail.ru/public/857J/LsFqwJwYA
Docs: https://vk.com/doc-65855514_445326637

Could you add support for them?

**Comment by nomakewan** [comment]
M3tox has already stated that DF 5.0 and older DF support is not planned, as DFET is intended to support DUST extraction and nothing else. See #4 and #6

**Comment by M3tox** [comment]
Right now DFET is intended to support only version 1.0 (DUST, most files) and 4.0 (Titanic: Adventure out of time, ALL files). Adding support to older, or newer versions is currently not planned.
Having an universal tool that can support all sorts of DreamFactory games would be amazing, but right now I want to spend my time and energy on other projects.

**Comment by Corak667** [comment]
You are right.
Ok, how about to complete support of DUST file formats?
Currently missed support:
set, prp, mov, flt

**Comment by M3tox** [comment]
Those are planned to be supported indeed, but I can't tell when these will be supported. These files appear so much more different from what I saw in version 4.0, that all files must be re-analyzed byte for byte. A very time consuming process. I may come back to this when I have the time and motivation for it again.
When all files of DUST are supported, DFET is considered to be done with the version 1.0 release.
